### ISSUE TITLE
Issue with price calculation

### ISSUE THREAD

**Issue by wfreq** [chartexpro/feature-requests-bugs#8]
Hello.. I've notice discrepancies when looking at charts vs trading.. prices are often off pretty significantly. I suspect an issue with how chart data is being plotted.

Example

![image](https://user-images.githubusercontent.com/71689306/93849111-24a3dc80-fc60-11ea-9a8a-aa8d02153871.png)
As you can see, the price data shows NEWTON at just over 21 cents.
Which should equal $210 per 1000, 

![image](https://user-images.githubusercontent.com/71689306/93849181-5cab1f80-fc60-11ea-9e65-888e835a948c.png)
As you can see the price given is almost 10% lower than what the chart shows

Ive noticed this on many other coins too, but this is the first time I've dug deeply into it.

Anyways hope this helps

**Comment by chartexpro** [comment]
Please be aware that the Uniswap prices quoted are not the current price rather what it anticipates the order will fill at based on the amount you've requested to buy or sell - it also factors in slippage.

ChartEx charts reflect the LAST trade price which you can verify from 'Show Trades' which is an accurate reflection of what has happened, rather than a reflection of where your order may fill.

![image](https://user-images.githubusercontent.com/69810341/93854609-f816b180-fcad-11ea-8818-8874aebdcf37.png)
